# Generated by Django 5.0.6 on 2024-05-14 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='productimg',
            options={'verbose_name': 'Фото товара', 'verbose_name_plural': 'Фото товаров'},
        ),
    ]
